config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'
  resources :users
  resources :articles
  resources :votes
  resources :articles do
    resources :votes
  end
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/news', to: 'articles#news'
  get '/business', to: 'articles#business'
  get '/entertainment', to: 'articles#entertainment'
  get '/tech', to: 'articles#tech'
  get '/sports', to: 'articles#sports'
  get '/opinion', to: 'articles#opinion'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'user_id'
  has_one_attached :image
  has_many :votes
  is_impressionable
  validates :title, presence: true, length: { maximum: 50 }
  validates :text, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token

  before_save { self.email = email.downcase }
  has_secure_password
  has_many :articles
  has_many :votes
  validates :first_name, presence: true, length: { maximum: 15 }
  validates :last_name, presence: true, length: { maximum: 15 }
  validates :email, presence: true, length: { maximum: 40 }
  
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
    BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  impressionist :actions => [:show]

  def index
    @articles = Article.with_attached_image.all
    @top = @articles[0]

    @news = []
    @business = []
    @ent = []
    @tech = []
    @sports = []
    @op = []

    @articles.each do |article|
      @news << article if article&.category == 'news'
      @business << article if article&.category == 'business'
      @ent << article if article&.category == 'entertainment'
      @tech << article if article&.category == 'tech'
      @sports << article if article&.category == 'sports'
      @op << article if article&.category == 'opinion'
    end
  end

  def new
    @article = current_user.articles.build
  end

  def create
    @article = current_user.articles.build(article_params)

    if @article.save
      flash[:success] = 'Article created'
      redirect_to article_path(@article)
    else
      flash[:danger] = 'Error creating article'
    end
  end

  def show
    @article = Article.find(params[:id])
    @votes = @article.votes
    impressionist(@article)
  end

  def news
    @articles = Article.where(category: 'news').order(created_at: :desc)
  end

  def business
    @articles = Article.where(category: 'business').order(created_at: :desc)
  end

  def entertainment
    @articles = Article.where(category: 'entertainment').order(created_at: :desc)
  end

  def tech
    @articles = Article.where(category: 'tech').order(created_at: :desc)
  end

  def sports
    @articles = Article.where(category: 'sports').order(created_at: :desc)
  end

  def opinion
    @articles = Article.where(category: 'opinion').order(created_at: :desc)
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to root_path
    flash[:success] = 'Article deleted'
  end

  private

  def article_params
    params.require(:article).permit(:title, :image, :text, :category)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user&.authenticate(params[:session][:password])
      log_in user
      redirect_to root_url
    else
      flash[:danger] = 'Invalid email/password entered'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'User created'
      log_in @user
      remember @user
      redirect_to root_path
    else
      flash[:danger] = 'Error creating user'
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @articles = @user.articles
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :find_article
  before_action :find_vote, only: [:destroy]

  def create
    @vote = @article.votes.create(user_id: current_user.id)
    redirect_to article_path(@article)
  end

  def destroy
    @vote.destroy
    redirect_to article_path(@article)
  end

  private

  def find_article
    @article = Article.find(params[:article_id])
  end

  def find_vote
    @vote = @article.votes.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      @current_user = User.find_by(id: user_id)

      if user&.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/articles/_list.html.erb
<div class="article-list">
  <% @articles.each do |article| %>
    <div class="article">
      <div class="article-align">
        <% if article.image.attached? %>
          <img src="<%= (url_for(article.image)) %>">
        <% end %>
        <div class="article-heading">
          <h2><%= link_to article.title, article_path(article) %></h2>
          <p>Written by: <%= article.author.first_name %> <%= article.author.last_name %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/business.html.erb
<h1 class="section-title">Business</h1>
<%= render 'articles/list' %>

app/views/articles/culture.html.erb
<h1 class="section-title">Culture</h1>
<%= render 'articles/list' %>

app/views/articles/entertainment.html.erb
<h1 class="section-title">Entertainment</h1>
<%= render 'articles/list' %>

app/views/articles/index.html.erb
<div class="grid-container">
  <div class="main" style="background-image: url(<%= (url_for(@top.image)) %>)">
    <div>
      <h2><%= @top.title %></h2>
      <p><%= link_to "Read more...", article_path(@top) %></p>
    </div>
  </div>
  <div class="sports" style="background-image: url(<%= (url_for(@sports[0].image)) %>)">
    <h2><%= link_to "Sports", sports_path %></h2>
  </div>
  <div class="tech" style="background-image: url(<%= (url_for(@tech[0].image)) %>)">
    <h2><%= link_to "Technology", tech_path %></h2>
  </div>
  <div class="opinion" style="background-image: url(<%= (url_for(@op[0].image)) %>)">
    <h2><%= link_to "Opinion", opinion_path %></h2>
  </div>
  <div class="entertainment" style="background-image: url(<%= (url_for(@ent[0].image)) %>)">
    <h2><%= link_to "Entertainment", entertainment_path %></h2>
  </div>
  <div class="business" style="background-image: url(<%= (url_for(@business[0].image)) %>)">
    <h2><%= link_to "Business", business_path %></h2>
  </div>
  <div class="news" style="background-image: url(<%= (url_for(@news[0].image)) %>)">
    <h2><%= link_to "News", news_path %></h2>
  </div>
</div>

app/views/articles/new.html.erb
<div class="form-area">
  <h2>Submit an article</h2>
  <div>
    <%= form_with model: @article, method: "post" do |f| %>
      <%= f.text_field :title, placeholder: 'Enter article title here' %><br />
      <%= f.file_field :image %><br />
      <%= f.label "Category" %><br />
      <%= f.select :category, options_for_select([
        ['news', 'news'],
        ['business', 'business'],
        ['entertainment', 'entertainment'],
        ['tech', 'tech'],
        ['sports', 'sports'],
        ['opinion', 'opinion']])
      %><br />
      <%= f.label "Article Content" %><br />
      <%= f.text_area :text, placeholder: "Enter article content here", size: "70x20" %><br />
      <%= f.submit "Post" %>
    <% end %>
  </div>
</div>

app/views/articles/news.html.erb
<h1 class="section-title">News</h1>
<%= render 'articles/list' %>

app/views/articles/opinion.html.erb
<h1 class="section-title">Opinion</h1>
<%= render 'articles/list' %>

app/views/articles/show.html.erb
<div class="show">
  <h1><%= @article.title %></h1>
  <h3><%= @article.author.first_name %> <%= @article.author.last_name %></h3>
  <div class="counts">
    <div class="votes">
      <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-hand-thumbs-up" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd" d="M6.956 1.745C7.021.81 7.908.087 8.864.325l.261.066c.463.116.874.456 1.012.965.22.816.533 2.511.062 4.51a9.84 9.84 0 0 1 .443-.051c.713-.065 1.669-.072 2.516.21.518.173.994.681 1.2 1.273.184.532.16 1.162-.234 1.733.058.119.103.242.138.363.077.27.113.567.113.856 0 .289-.036.586-.113.856-.039.135-.09.273-.16.404.169.387.107.819-.003 1.148a3.163 3.163 0 0 1-.488.901c.054.152.076.312.076.465 0 .305-.089.625-.253.912C13.1 15.522 12.437 16 11.5 16v-1c.563 0 .901-.272 1.066-.56a.865.865 0 0 0 .121-.416c0-.12-.035-.165-.04-.17l-.354-.354.353-.354c.202-.201.407-.511.505-.804.104-.312.043-.441-.005-.488l-.353-.354.353-.354c.043-.042.105-.14.154-.315.048-.167.075-.37.075-.581 0-.211-.027-.414-.075-.581-.05-.174-.111-.273-.154-.315L12.793 9l.353-.354c.353-.352.373-.713.267-1.02-.122-.35-.396-.593-.571-.652-.653-.217-1.447-.224-2.11-.164a8.907 8.907 0 0 0-1.094.171l-.014.003-.003.001a.5.5 0 0 1-.595-.643 8.34 8.34 0 0 0 .145-4.726c-.03-.111-.128-.215-.288-.255l-.262-.065c-.306-.077-.642.156-.667.518-.075 1.082-.239 2.15-.482 2.85-.174.502-.603 1.268-1.238 1.977-.637.712-1.519 1.41-2.614 1.708-.394.108-.62.396-.62.65v4.002c0 .26.22.515.553.55 1.293.137 1.936.53 2.491.868l.04.025c.27.164.495.296.776.393.277.095.63.163 1.14.163h3.5v1H8c-.605 0-1.07-.081-1.466-.218a4.82 4.82 0 0 1-.97-.484l-.048-.03c-.504-.307-.999-.609-2.068-.722C2.682 14.464 2 13.846 2 13V9c0-.85.685-1.432 1.357-1.615.849-.232 1.574-.787 2.132-1.41.56-.627.914-1.28 1.039-1.639.199-.575.356-1.539.428-2.59z"/>
      </svg>
      <p><%= @article.votes.size %></p>
    </div>
    <div class="views">
      <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-eye-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
        <path d="M10.5 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0z"/>
        <path fill-rule="evenodd" d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8zm8 3.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7z"/>
      </svg>
      <p><%= @article.impressionist_count %></p>
    </div>
  </div>
  

  <% current_vote = @article.votes.find { |vote| vote.user_id == current_user.id } %>
  <% user_article = Article.where { |article| article.user_id == current_user.id } %>

  <% if current_user %>
    <% if current_vote %>
      <%= button_to 'Down-vote', article_vote_path(@article, current_vote), method: :delete %>
    <% else %>
      <%= button_to 'Up-vote', article_votes_path(@article), method: :post %>
    <% end %>
  <% else %>
    <button class="hidden"></button>
  <% end %>

  <% if @article.image.attached? %>
    <img class="art-img" src="<%= (url_for(@article.image)) %>">
  <% end %>

</div>
<div class="article-content">
  <p><%= @article.text %></p>
</div>

app/views/articles/sports.html.erb
<h1 class="section-title">Sports</h1>
<%= render 'articles/list' %>

app/views/articles/tech.html.erb
<h1 class="section-title">Technology</h1>
<%= render 'articles/list' %>

app/views/layouts/_footer.html.erb
<footer>
  <span>Made in 2020 by Kerron King</span>
</footer>

app/views/layouts/_header.html.erb
<nav id="nav">
  <div class="logo">
    <span><%= link_to "Kalugera", root_path %></span>
  </div>
  <ul>
    <li><%= link_to "News", news_path %></li>
    <li><%= link_to "Business", business_path %></li>
    <li><%= link_to "Entertainment", entertainment_path %></li>
    <li><%= link_to "Tech", tech_path %></li>
    <li><%= link_to "Sports", sports_path %></li>
    <li><%= link_to "Opinion", opinion_path %></li>
  </ul>
  <div class="logs">
    <% if logged_in? %>
      <span><%= link_to "Profile", user_path(current_user) %></span>
      <span><%= link_to "New Article", new_article_path %></span>
      <span><%= link_to "Log out", logout_path, method: :delete %></span>
    <% else %>
      <span><%= link_to "Log in", login_path %></span>
      <span><%= link_to "Sign up", new_user_path %></span>
    <% end %>
  </div>
  <button
    id="icon"
  >
    <i class="fa fa-bars fa-2x"></i>
  </button>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kalugera</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta content="width=device-width, initial-scale=1" name="viewport" />
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <% flash.each do |message| %>
      <div><% message %></div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= javascript_pack_tag 'dropdown' %>
  </body>
</html>

app/views/users/new.html.erb
<div class="form-area">
  <h1>Sign Up</h1>
  <div>
    <%= form_with model: @user, method: "post" do |f| %>
      <%= f.text_field :first_name, placeholder: "Enter your first name" %><br />
      <%= f.text_field :last_name, placeholder: "Enter your last name" %><br />
      <%= f.email_field :email, placeholder: "Enter your email" %><br />
      <%= f.password_field :password, placeholder: "Enter your password" %><br />
      <%= f.submit "Create" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h1><%= @user.first_name%> <%= @user.last_name%></h1>
<%= render 'articles/list' %>

app/views/votes/create.html.erb
<h1>Votes#create</h1>
<p>Find me in app/views/votes/create.html.erb</p>

app/views/votes/destroy.html.erb
<h1>Votes#destroy</h1>
<p>Find me in app/views/votes/destroy.html.erb</p>

app/views/votes/new.html.erb
<h1>Votes#new</h1>
<p>Find me in app/views/votes/new.html.erb</p>